# Generated by Django 5.0.6 on 2024-09-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountwallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accountwallet',
        ),
    ]
