# Generated by Django 5.0.6 on 2024-10-14 09:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeChequiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque_debut', models.CharField(max_length=10)),
                ('numero_cheque_fin', models.CharField(max_length=10)),
                ('motif', models.TextField()),
                ('est_traite', models.BooleanField(default=False)),
                ('demande_le', models.DateTimeField(auto_now_add=True)),
                ('nombre_pages', models.IntegerField(choices=[(25, '25 pages'), (50, '50 pages')], validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(50)])),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
