# Generated by Django 5.1.1 on 2025-03-27 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_demandechequiers'),
        ('transactions', '0009_remove_transaction_destination_wallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='account',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('PENDING', 'En attente'), ('BLOCKED', 'Bloqué'), ('CLOSED', 'Fermé')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('business', 'Business'), ('agency', 'Agency'), ('commission', 'Commission')], default='wallet', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
