# Generated by Django 5.1.1 on 2025-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('personnel', 'Personnel'), ('business', 'Business'), ('agency', 'Agency'), ('intern', 'Intern')], default='personnel', max_length=50),
        ),
    ]
