# Generated by Django 5.1.1 on 2025-04-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_code_alter_account_type_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='purpose',
            field=models.CharField(blank=True, choices=[('commission', 'Commission'), ('frais', 'Frais'), ('taxe', 'Taxe'), ('reserve', 'Reserve')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
