# Generated by Django 5.1.1 on 2025-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_purpose_alter_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_bank',
            field=models.BooleanField(default=True),
        ),
    ]
