# Generated by Django 5.1.1 on 2025-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_commission_percentage_account_parent_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='commission_percentage',
            new_name='deposit_porcentage',
        ),
        migrations.RemoveField(
            model_name='account',
            name='parent_bank',
        ),
        migrations.AddField(
            model_name='account',
            name='retrai_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
