# Generated by Django 5.0.6 on 2024-08-18 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('transactions', '0002_alter_transaction_source_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RELEVE', 'Relevé de compte'), ('CHEQUIER', 'Chéquier'), ('CARTE', 'Carte bancaire')], max_length=20)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de traitement'), ('TERMINE', 'Terminé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='accounts.account')),
            ],
        ),
    ]
