# Generated by Django 5.0.6 on 2024-10-10 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wallet'),
        ('transactions', '0006_transaction_external_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='accounts.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_transactions', to='accounts.wallet'),
        ),
    ]
