# Generated by Django 5.0.6 on 2024-10-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_destination_wallet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demande',
        ),
    ]
