# Generated by Django 5.1.1 on 2025-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_delete_demande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destination_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_wallet',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
