# Generated by Django 5.1.1 on 2025-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_pretransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('paiement', 'Paiement')], max_length=50)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['max_amount'],
            },
        ),
    ]
