# Generated by Django 5.1.1 on 2025-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretransaction',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
