# Generated by Django 5.1.1 on 2025-06-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('reset_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'password_reset_otp',
                'indexes': [models.Index(fields=['phone_number'], name='password_re_phone_n_6bfc22_idx'), models.Index(fields=['otp_code'], name='password_re_otp_cod_3b18b3_idx'), models.Index(fields=['reset_token'], name='password_re_reset_t_3f19ef_idx'), models.Index(fields=['created_at'], name='password_re_created_4ee1aa_idx')],
            },
        ),
    ]
