# Generated by Django 5.1.1 on 2025-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_merchant_remove_user_merchant_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='merchant_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
