# Generated by Django 5.1.1 on 2025-03-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_user_is_merchant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_merchant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='merchant_code',
        ),
    ]
