# Generated by Django 5.1.1 on 2025-05-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_bank_code_user_is_super_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_super_admin',
        ),
    ]
