# Generated by Django 5.1.1 on 2025-05-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBankSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Sélectionner la banque courante',
                'verbose_name_plural': 'Sélectionner la banque courante',
                'managed': False,
            },
        ),
    ]
