# Generated by Django 5.2.1 on 2025-06-19 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminselect', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupApiPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(help_text='Nom de la vue API (ex: TransactionHistoryView)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Activer/désactiver cette permission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Permission API Groupe',
                'verbose_name_plural': 'Permissions API Groupe',
                'unique_together': {('group', 'view_name')},
            },
        ),
        migrations.CreateModel(
            name='UserApiPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(help_text='Nom de la vue API', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Activer/désactiver cette permission')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin_override', models.BooleanField(default=False, help_text="Permission spécifique pour admin (override l'accès complet)")),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission API Utilisateur',
                'verbose_name_plural': 'Permissions API Utilisateur',
                'unique_together': {('user', 'view_name')},
            },
        ),
    ]
